# Generated by Django 5.0.1 on 2024-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDonorsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_Name', models.CharField(max_length=50)),
                ('Donor_Email', models.EmailField(max_length=254)),
                ('Donor_Phone', models.CharField(max_length=15)),
                ('Donor_Amount', models.IntegerField()),
                ('Donor_Scholarships', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedScholarshipsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholarship_name', models.CharField(max_length=50)),
                ('Scholarship_Amount', models.IntegerField()),
                ('Scholarship_Donor_name', models.CharField(max_length=50)),
                ('Scholarship_Donor_email', models.EmailField(max_length=254)),
                ('Scholarship_Donor_phone', models.CharField(max_length=15)),
                ('Scholarships_Avaliable', models.IntegerField()),
                ('Scholarships_Majors_Minors', models.CharField(max_length=50)),
                ('Scholarships_GPA', models.FloatField()),
                ('Scholarships_Deadline', models.DateField()),
                ('Scholarships_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AvailableScholarshipsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholarship_name', models.CharField(max_length=50)),
                ('Scholarship_Amount', models.IntegerField()),
                ('Scholarship_Donor_name', models.CharField(max_length=50)),
                ('Scholarship_Donor_email', models.EmailField(max_length=254)),
                ('Scholarship_Donor_phone', models.CharField(max_length=15)),
                ('Scholarships_Avaliable', models.IntegerField()),
                ('Scholarships_Majors_Minors', models.CharField(max_length=50)),
                ('Scholarships_GPA', models.FloatField()),
                ('Scholarships_Deadline', models.DateField()),
                ('Scholarships_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AwardedScholarshipReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholarship_Name', models.CharField(max_length=50)),
                ('Scholarship_Amount', models.IntegerField()),
                ('Student_Awarded_Name', models.CharField(max_length=50)),
                ('Student_Awarded_NetID', models.CharField(max_length=50)),
                ('Student_Awarded_Major', models.CharField(max_length=50)),
                ('Student_Awarded_GPA', models.FloatField()),
                ('Student_Awarded_Ethnicity', models.CharField(max_length=50)),
                ('Student_Awarded_Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ScholarshipApplicationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scholarship_Name', models.CharField(max_length=50)),
                ('Applicant_Name', models.CharField(max_length=50)),
                ('Applicant_Pronouns', models.CharField(max_length=50)),
                ('Applicant_NetID', models.CharField(max_length=50)),
                ('Applicant_Major', models.CharField(max_length=50)),
                ('Applicant_GPA', models.FloatField()),
                ('Applicant_Year', models.CharField(max_length=50)),
                ('Applicant_Ethnicity', models.CharField(max_length=50)),
                ('Applicant_Personal_Statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDemographicsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('Student_NetID', models.CharField(max_length=50)),
                ('Student_Major', models.CharField(max_length=50)),
                ('Student_GPA', models.FloatField()),
                ('Student_Year', models.CharField(max_length=50)),
                ('Student_Ethnicity', models.CharField(max_length=50)),
                ('Student_Personal_Statement', models.TextField()),
            ],
        ),
    ]
