stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: gsears72/sfwe_s24_402_uasams
  IMAGE_TAG: umas-0.1.0

run_test:
  tags:
    - test
  stage: test
  image: python:3.12.1-bookworm
  before_script:
    - python -m pip install -r requirements.txt
  script:
    - python manage.py test

build_image:
  tags:
    - test
  stage: build
  image: docker
  services:
    - docker:dind

  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy:
  tags:
    - test
  stage: deploy
  when: manual
  before_script:
    - chmod 400 $SSH_KEY
  script:
   - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@147.182.255.74 "
      docker login -u $DOCKER_USER -p $DOCKER_PASS && 
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p5000:5000 $IMAGE_NAME:$IMAGE_TAG
    "