stages:
  -test
  -build
  -deploy

run_test:
  stage: test
  image: python:3.12.1-bookworm
  before_script:
    - apt-get && apt-get install make
  script:
    - make test

build_image:
  stage: build
  image: docker:25.0.0-rc.2-cli
  services:
    - docker:25.0.0-rc.2-dind
  variables:
   DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t ########/SFWE402:SFWE-Scholarships
    - docker push ########/SFWE402:SFWE-Scholarships

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
   - ssh StrictHostKeyChecking=no -i $SSH_KEY root@ "
      docker login -u $DOCKER_USER -p $DOCKER_PASS && 
      docker ps -aq | xargs docker stop | xargs docker rm &&
      docker run -d -p5000:5000 ########/SFWE402:SFWE-Scholarships
    "
