# Generated by Django 5.0.1 on 2024-03-20 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=100)),
                ('scholarship_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_full_name', models.CharField(max_length=100)),
                ('donor_phone_number', models.CharField(max_length=15)),
                ('donor_email', models.EmailField(max_length=254)),
                ('num_scholarships_available', models.IntegerField()),
                ('required_majors_or_minors', models.CharField(choices=[('Engineering', 'Engineering'), ('Business', 'Business'), ('Music', 'Music'), ('Art', 'Art'), ('Performing Arts', 'Performing Arts'), ('Theater Tech', 'Theater Tech'), ('Photography', 'Photography'), ('Nursing', 'Nursing'), ('Computer Science', 'Computer Science'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Literature', 'Literature'), ('Writing', 'Writing'), ('Foreign Language', 'Foreign Language'), ('Law', 'Law'), ('Medicine', 'Medicine'), ('Communications', 'Communications'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Ecomomics', 'Economics'), ('Math', 'Math'), ('Environmental Science', 'Environmental Science'), ('Public Health', 'Public Health'), ('Graphic Design', 'Graphic Design'), ('Architecture', 'Architecture'), ('Education', 'Education'), ('Astronomy', 'Astronomy'), ('Social Sciences', 'Social Sciences'), ('Fashion', 'Fashion'), ('Statistics', 'Statistics'), ('Geology', 'Geology'), ('Neuroscience', 'Neuroscience'), ('Psychology', 'Psychology'), ('none', 'none')], max_length=30)),
                ('required_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('application_deadline', models.DateField()),
                ('other_requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_info', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
