# Generated by Django 5.0.1 on 2024-02-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('security_question_1', models.CharField(max_length=100)),
                ('security_answer_1', models.CharField(max_length=100)),
                ('security_question_2', models.CharField(max_length=100)),
                ('security_answer_2', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('net_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=100)),
                ('scholarship_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donor_full_name', models.CharField(max_length=100)),
                ('donor_phone_number', models.CharField(max_length=15)),
                ('donor_email', models.EmailField(max_length=254)),
                ('num_scholarships_available', models.IntegerField()),
                ('required_majors_or_minors', models.CharField(max_length=200)),
                ('required_gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('application_deadline', models.DateField()),
                ('other_requirements', models.TextField()),
            ],
        ),
    ]
