# Generated by Django 5.0.1 on 2024-03-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='jxwpwfseyv@test.com', max_length=60, unique=True, verbose_name='email'),
        ),
    ]
