# Generated by Django 5.0.1 on 2024-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='cblubfxfnh@mydomain.com', max_length=60, unique=True, verbose_name='email'),
        ),
    ]
