# Generated by Django 5.0.1 on 2024-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='swmknmnkbf@mydomain.com', max_length=60, unique=True, verbose_name='email'),
        ),
    ]
