# Generated by Django 5.0.1 on 2024-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='lqjskscybc@example.com', max_length=60, unique=True, verbose_name='email'),
        ),
    ]
