# Generated by Django 5.0.2 on 2024-05-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='tunbvzwxsd@mydomain.com', max_length=60, unique=True, verbose_name='email'),
        ),
    ]
