# Generated by Django 5.0.1 on 2024-02-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('security_question_1', models.CharField(max_length=100)),
                ('security_answer_1', models.CharField(max_length=100)),
                ('security_question_2', models.CharField(max_length=100)),
                ('security_answer_2', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('net_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_pronoun', models.CharField(blank=True, max_length=20, null=True)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('current_year', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], max_length=20)),
                ('ethnicity', models.CharField(choices=[('Caucasian', 'Caucasian'), ('Hispanic', 'Hispanic'), ('Black', 'Black'), ('European', 'European'), ('Asian', 'Asian'), ('Indian', 'Indian'), ('American Indian', 'American Indian'), ('Arabic/Middle Eastern', 'Arabic/Middle Eastern'), ('Other', 'Other')], max_length=30)),
                ('personal_statement_essay', models.TextField()),
                ('work_experience', models.TextField()),
            ],
        ),
    ]
