# Generated by Django 5.0.1 on 2024-03-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFWEScholarships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='essay',
            new_name='personal_statement',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='stauts',
            new_name='status',
        ),
    ]
