# Generated by Django 5.0.1 on 2024-02-15 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFWEScholarships', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
