# Generated by Django 5.0.1 on 2024-03-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFWEScholarships', '0002_rename_essay_application_personal_statement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='stauts',
        ),
    ]
