# Generated by Django 5.0.1 on 2024-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWEScholarships', '0003_rename_status_application_stauts'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='application',
            name='sr_status',
            field=models.CharField(choices=[('In Reivew', 'In Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='In Review', max_length=20),
        ),
    ]
