# Generated by Django 5.0.1 on 2024-04-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWEScholarships', '0004_application_score_application_sr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(default='resumes/default.pdf', upload_to='resumes/'),
        ),
    ]
