# Generated by Django 5.0.1 on 2024-04-27 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFWEScholarships', '0005_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
        migrations.AlterField(
            model_name='application',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
